##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################
---
{{- if .Values.global.cluster.cloudNativeServices }}
{{- if eq .Values.global.cluster.provider "aws" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-secret-manager-script
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "scripts/aws-secret-manager-script.py").AsConfig | indent 2 }}
{{- end }}
{{- else }}
{{- if eq .Values.global.vault.type "hashicorp" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: bevel-vault-script
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "scripts/bevel-vault.sh").AsConfig | indent 2 }}
{{- end }}
{{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: package-manager
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "scripts/package-manager.sh").AsConfig | indent 2 }}
